version: "3.9"

services:
  postgres:
    image: postgres:16.6
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: agile_assessment_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Aavn1234567890~
    volumes:
      - postgres_data:/var/lib/postgresql/data

  agile-assessment-api:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: agile-assessment-api
    ports:
      - "8080:8080"
      - "9990:9990"
    environment:
      DATASOURCE_NAME: PostgresDS
      DATASOURCE_JNDI: java:jboss/jdbc/PostgresDS
      POSTGRESQL_VERSION: 42.6.0
      JBOSS_HOME: /opt/jboss/wildfly
      VALID_CONNECTION_CHECKER: org.jboss.jca.adapters.jdbc.extensions.postgres.PostgreSQLValidConnectionChecker
    depends_on:
      - postgres
    volumes:
      - ./target:/app/target
      - maven_cache:/root/.m2

volumes:
  postgres_data:
  maven_cache:
